services:
  python-env:
    image: "ubuntu-3.6.2:v3"
    container_name: env-3.6.2
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "10362:22"
      - "8080:8080"
    # root
    privileged: true
    # 对应 -i
    stdin_open: true
    # 对应 -t
    tty: true
    entrypoint: [ "sh" ]
    networks:
      - common-network


  mysql:
    image: "mysql:8.0.30"
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/logs:/var/log/mysql"
    # root
    privileged: true
    networks:
      - common-network

  redis:
    image: "redis:6.0.16"
    container_name: redis-server
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
      - "./redis/logs/redis.log:/var/log/redis/redis.log"
      - "./redis/data:/data"
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    # root
    privileged: true
    networks:
      - common-network


# 定义共享网络
networks:
  common-network:
    name: common-network
    driver: bridge
