services:
  python-env:
    build:
      context: .  # 上下文路径为当前目录
      dockerfile: Dockerfile  # 指定 Dockerfile 的相对路径
    container_name: env-3.12
    environment:
      TZ: "UTC"  # 设置时区为 UTC
    ports:
      - "10022:22"  # 映射主机的 10222 端口到容器的 22 端口，用于 SSH 连接
      - "8080:8080"  # 映射主机的 8080 端口到容器的 8080 端口（如果需要）
    privileged: true  # 开启特权模式，允许容器执行某些操作（如访问宿主机硬件）
    stdin_open: true  # 保持容器的标准输入打开
    tty: true  # 分配伪终端
    entrypoint: [ "sh" ]  # 默认启动 shell，可以更改为其他命令
    networks:
      - common-network  # 使用共享网络

# 定义共享网络
networks:
  common-network:
    name: common-network
    driver: bridge