version: '3.6'
services:
  python-env:
    image: "3.10.4:yidrone"
    container_name: env-3.10.4
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "10310:22"
      - "10362:10362"
      - "8080:8080"
      - "3306:3306"
      - "6010:6010"
      - "5010:5010"
      - "6379:6379"
    # root
    privileged: true
    # 对应 -i
    stdin_open: true
    # 对应 -t
    tty: true
    entrypoint: [ "sh" ]


  py-3.6.2:
    image: "3.6.2:v1"
    container_name: env-3.6.2
    environment:
      TZ: "Asia/Shanghai"
    network_mode: "service:python-env"
    # root
    privileged: true
    # 对应 -i
    stdin_open: true
    # 对应 -t
    tty: true
    entrypoint: [ "sh" ]


  mysql:
    image: "mysql:8.0.30"
    container_name: mysql
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/logs:/var/log/mysql"
    network_mode: "service:python-env"
    # root
    privileged: true
    depends_on:
      - python-env
    restart: always

  redis:
    image: "redis:6.0.16"
    container_name: redis
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
      - "./redis/logs/redis.log:/var/log/redis/redis.log"
      - "./redis/data:/data"
    command: ["redis-server", "/etc/redis/redis.conf"]
    network_mode: "service:python-env"
    # root
    privileged: true
    depends_on:
      - python-env
    restart: always

