version: '3.6'
services:
  python-env:
    # 可以更换成自己的dockerfile
    #    build:
    #      context: ./env-build-3.6.2
    #      dockerfile: Dockerfile
    # 镜像名字,自己命名
    image: "py-3.10.4:v1"
    container_name: env-3.10.4
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "10010:22"
      - "8080:8080"
      - "3306:3306"
      - "27017:27017"
      - "6010:6010"
      - "5010:5010"
    #  - "18002:18002"
    #      - "6379:6379"
    #      - "9200:9200"
    #      - "9300:9300"
    #      - "5001:5001"
    #      - "8123:8123"
    #      - "9000:9000"
    #      - "9009:9009"

    # root
    privileged: true
    # 对应 -i
    stdin_open: true
    # 对应 -t
    tty: true
    entrypoint: [ "sh" ]

  go-env:
    image: golang:latest
    container_name: go-env-3.10.4
    environment:
      TZ: "Asia/Shanghai"
    network_mode: "service:python-env"
    restart: always

  mysql:
    image: "mysql:latest"
    container_name: mysql
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "123456"
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/logs:/var/log/mysql"
      - "./mysql/mysql-files:/var/lib/mysql-files"
    #    ports:
    #      - "3306:3306"
    network_mode: "service:python-env"
    restart: always


  redis:
    image: "redis:latest"
    container_name: redis
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
      - "./redis/logs/redis.log:/var/log/redis/redis.log"
      - "./redis/data:/data"
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    network_mode: "service:python-env"
    restart: always


    #  mongodb:
    #    image: "mongo:latest"
    #    container_name: mongodb
    #    environment:
    #      TZ: "Asia/Shanghai"
    #    volumes:
    #      - "./mongodb/db:/data/db"
    #      - "./mongodb/config/mongod.conf:/etc/mongod.conf"
    #      - "./mongodb/logs/mongod.log:/var/log/mongodb/mongod.log"
    #    #    ports:
    #    #      - "27017:27017"
    #    network_mode: "service:python-env"
    #    restart: always


    #  elasticsearch:
    #    image: "elasticsearch:5.5.0"
    #    container_name: elasticsearch
    #    environment:
    #      TZ: "Asia/Shanghai"
    #      discovery.type: "single-node"
    #      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    #    volumes:
    #      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    #      - "./elasticsearch/data:/usr/share/elasticsearch/data"
    #      - "./elasticsearch/logs:/usr/share/elasticsearch/logs"
    #      - "./elasticsearch/ik:/usr/share/elasticsearch/plugins/ik"
    #    #    ports:
    #    #      - "9200:9200"
    #    #      - "9300:9300"
    #    network_mode: "service:python-env"
    #    restart: always


    #  clickhouse-server:
    #    image: "clickhouse/clickhouse-server:latest"
    #    container_name: clickhouse-server
    #    environment:
    #      TZ: "Asia/Shanghai"
    #    ulimits:
    #      nproc: 65535
    #      nofile:
    #        soft: 262144
    #        hard: 262144
    #    volumes:
    #      - "./clickhouse/data:/var/lib/clickhouse"
    #      - "./clickhouse/config/config.xml:/etc/clickhouse-server/config.xml"
    #      - "./clickhouse/config/users.xml:/etc/clickhouse-server/users.xml"
    #      - "./clickhouse/logs:/var/log/clickhouse-server"
    #    ports:
    #      - "8123:8123"
    #      - "9000:9000"
    #      - "9009:9009"
#    network_mode: "service:python-env"
#    restart: always
